// PAGES
export const FETCH_PAGES = 'FETCH_PAGES';
export const FETCH_PAGES_FULFILLED = 'FETCH_PAGES_FULFILLED';
// TOPICS
export const FETCH_TOPICS = 'FETCH_TOPICS';
export const FETCH_TOPICS_FULFILLED = 'FETCH_TOPICS_FULFILLED';